
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertTrue;

import org.junit.Ignore;
import org.junit.Test;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import annotation.QuartzConfiguration;

public class LibraryTest {
	@Ignore
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}

	public static void main(String[] args) {
		new ClassPathXmlApplicationContext("quartz.xml");
		// new AnnotationConfigApplicationContext(annotation.QuartzConfiguration.class);
	}
}
